version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio-test
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Web UI
    environment:
      - MINIO_ROOT_USER=testtest
      - MINIO_ROOT_PASSWORD=testtest
    command: server /data --console-address ":9001"