packages:
  - 'api/**'
  - 'client/**'
  - 'shared/**'
  - 'e2e/**'
  - 'data/**'
  - 'admin/**'


catalog:
  pg: "8.12.0"
  typeorm: "0.3.20"
  zod: "3.23.8"
  class-transformer: "0.5.1"
  bcrypt: "5.1.1"
  "@types/node": 20.14.2
  "@types/geojson": 7946.0.14
  typescript: 5.4.5
  reflect-metadata: "^0.2.0"
  class-validator: "0.14.1"
  nestjs-base-service: "0.11.1"