packages:
  - 'api/**'
  - 'client/**'
  - 'shared/**'
  - 'e2e/**'
  - 'data/**'
  - 'backoffice/**'


catalog:
  pg: "8.14.1"
  typeorm: "0.3.25"
  zod: "3.25.28"
  class-transformer: "0.5.1"
  bcrypt: "5.1.1"
  "@types/node": 22.15.21
  "@types/geojson": 7946.0.16
  typescript: 5.8.3
  reflect-metadata: "^0.2.0"
  class-validator: "0.14.1"
  nestjs-base-service: "0.11.1"