packages:
  - 'api/**'
  - 'client/**'
  - 'shared/**'


catalog:
  pg: "8.12.0"
  typeorm: "0.3.20"
  zod: "3.23.8"
  class-transformer: "0.5.1"
  bcrypt: "5.1.1"
  "@types/node": 20.14.2
  typescript: 5.4.5