// TODO: we need to clearly know which fields are required to create a project, and which are generated by the system

import {
    ConservationProjectParametersSchema,
    CreateProjectSchema,
    RestorationProjectParametersSchema
} from "@shared/schemas/projects/create-project.schema";
import { z } from "zod";

export type CreateProjectDto = z.infer<typeof CreateProjectSchema>;

export type RestorationProjectParameters = z.infer<typeof RestorationProjectParametersSchema>;

export type ConservationProjectParameters = z.infer<typeof ConservationProjectParametersSchema>


