// TODO: we need to clearly know which fields are required to create a project, and which are generated by the system

import { CreateProjectSchemaBCK } from "@shared/schemas/projects/create-project.schema";
import { z } from "zod";

export type CreateProjectDto = z.infer<typeof CreateProjectSchemaBCK>;
