import { ACTIVITY, ECOSYSTEM } from '@shared/entities/base-data.entity';
import { COMMUNITY_CASH_FLOW_TYPES } from '@shared/entities/community-cash-flow.entity';

export type BaseDataJson = {
  country: string;
  ecosystem: ECOSYSTEM;
  activity: ACTIVITY;
  country_code: string;
  continent: string;
  hdi: number;
  project_size_ha: number;
  feasibility_analysis: number;
  conservation_planning_and_admin: number;
  data_collection_and_field_costs: number;
  community_representation: number;
  blue_carbon_planning: number;
  establishing_carbon_rights: number;
  financing_cost: number;
  validation: number;
  implementation_labor_planting: number;
  implementation_labor_hybrid: number;
  implementation_labor_hydrology: number;
  monitoring: number;
  maintenance: number;
  maintenance_duration: number;
  carbon_standard_fees: number;
  community_benefit_sharing_fund: number;
  baseline_reassessment: number;
  MRV: number;
  long_term_project_operating_cost: number;
  ecosystem_extent: number;
  ecosystem_extent_historic: number;
  ecosystem_loss_rate: number;
  restorable_land: number;
  // TODO: Since this is the value that is selected in the corresponding tab within different tiers, maybe the naming is a bit confusing, talk with Elena
  tier_1_emission_factor: string;
  emission_factor_AGB: number;
  emission_factor_SOC: number;
  sequestration_rate: number;
  other_community_cash_flow: COMMUNITY_CASH_FLOW_TYPES;
};
