import { ExcelBaseIncrease } from '@api/modules/import/dtos/excel-base-increase.dto';
import { ExcelBaseSize } from '@api/modules/import/dtos/excel-base-size.dto';
import { ExcelBaselineReassessment } from '@api/modules/import/dtos/excel-baseline-reassessment.dto';
import { ExcelBlueCarbonProjectPlanning } from '@api/modules/import/dtos/excel-blue-carbon-project-planning.dto';
import { ExcelCarbonStandardFees } from '@api/modules/import/dtos/excel-carbon-standard-fees.dto';
import { ExcelEcosystemLoss } from '@api/modules/import/dtos/excel-ccosystem-loss.dto';
import { ExcelCommunityBenefitSharingFund } from '@api/modules/import/dtos/excel-community-benefit-sharing-fund.dto';
import { ExcelCommunityCashFlow } from '@api/modules/import/dtos/excel-community-cash-flow.dto';
import { ExcelCommunityRepresentation } from '@api/modules/import/dtos/excel-community-representation.dto';
import { ExcelConservationPlanningAndAdmin } from '@api/modules/import/dtos/excel-conservation-planning-and-admin.dto';
import { ExcelDataCollectionAndFieldCosts } from '@api/modules/import/dtos/excel-data-collection-field-cost.dto';
import { ExcelEcosystemExtent } from '@api/modules/import/dtos/excel-ecosystem-extent.dto';
import { ExcelEmissionFactors } from '@api/modules/import/dtos/excel-emission-factors.dto';
import { ExcelEstablishingCarbonRights } from '@api/modules/import/dtos/excel-establishing-carbon-rights.dto';
import { ExcelFeasibilityAnalysis } from '@api/modules/import/dtos/excel-feasibility-analysis.dto';
import { ExcelFinancingCost } from '@api/modules/import/dtos/excel-financing-cost.dto';
import { ExcelImplementationLaborCost } from '@api/modules/import/dtos/excel-implementation-labor.dto';
import { ExcelLongTermProjectOperating } from '@api/modules/import/dtos/excel-long-term-project-operating.dto';
import { ExcelMaintenance } from '@api/modules/import/dtos/excel-maintenance.dto';
import { ExcelModelAssumptions } from '@api/modules/import/dtos/excel-model-assumptions.dto';
import { ExcelMonitoring } from '@api/modules/import/dtos/excel-monitoring.dto';
import { ExcelMRV } from '@api/modules/import/dtos/excel-mrv.dto';
import { ExcelProjectSize } from '@api/modules/import/dtos/excel-project-size.dto';
import { ExcelProject } from '@api/modules/import/dtos/excel-projects.dto';
import { ExcelRestorableLand } from '@api/modules/import/dtos/excel-restorable-land.dto';
import { ExcelSequestrationRate } from '@api/modules/import/dtos/excel-sequestration-rate.dto';
import { ExcelValidation } from '@api/modules/import/dtos/excel-validation.dto';

export type RawDataIngestionData = {
  Projects: ExcelProject[];
  'Project size': ExcelProjectSize[];
  'Feasibility analysis': ExcelFeasibilityAnalysis[];
  'Conservation planning and admin': ExcelConservationPlanningAndAdmin[];
  'Data collection and field costs': ExcelDataCollectionAndFieldCosts[];
  'Community representation': ExcelCommunityRepresentation[];
  'Blue carbon project planning': ExcelBlueCarbonProjectPlanning[];
  'Establishing carbon rights': ExcelEstablishingCarbonRights[];
  'Financing cost': ExcelFinancingCost[];
  Validation: ExcelValidation[];
  Monitoring: ExcelMonitoring[];
  Maintenance: ExcelMaintenance[];
  'Community benefit sharing fund': ExcelCommunityBenefitSharingFund[];
  'Baseline reassessment': ExcelBaselineReassessment[];
  MRV: ExcelMRV[];
  'Long-term project operating': ExcelLongTermProjectOperating[];
  'Carbon standard fees': ExcelCarbonStandardFees[];
  'Community cash flow': ExcelCommunityCashFlow[];
  'Ecosystem extent': ExcelEcosystemExtent[];
  'Ecosystem loss': ExcelEcosystemLoss[];
  'Restorable land': ExcelRestorableLand[];
  'Sequestration rate': ExcelSequestrationRate[];
  'Emission factors': ExcelEmissionFactors[];
  'Implementation labor': ExcelImplementationLaborCost[];
  base_size_table: ExcelBaseSize[];
  base_increase: ExcelBaseIncrease[];
  'Model assumptions': ExcelModelAssumptions[];
};
