import {
  ACTIVITY,
  RESTORATION_ACTIVITY_SUBTYPE,
} from '@shared/entities/activity.enum';
import { ECOSYSTEM } from '@shared/entities/ecosystem.enum';
import { PROJECT_PRICE_TYPE } from '@shared/entities/projects.entity';

export type ExcelProject = {
  project_name: string;
  continent: string;
  country: string;
  country_code: string;
  ecosystem: ECOSYSTEM;
  activity: ACTIVITY;
  activity_type: RESTORATION_ACTIVITY_SUBTYPE;
  project_size_ha: number;
  project_size_filter: string;
  abatement_potential: number;
  total_cost_npv: number;
  total_cost: number;
  capex_npv: number;
  capex: number;
  opex_npv: number;
  opex: number;
  cost_per_tco2e_npv: number;
  cost_per_tco2e: number;
  feasibility_analysis_npv: number;
  feasibility_analysis: number;
  conservation_planning_npv: number;
  conservation_planning: number;
  data_collection_npv: number;
  data_collection: number;
  community_representation_npv: number;
  community_representation: number;
  blue_carbon_project_planning_npv: number;
  blue_carbon_project_planning: number;
  establishing_carbon_rights_npv: number;
  establishing_carbon_rights: number;
  validation_npv: number;
  validation: number;
  implementation_labor_npv: number;
  implementation_labor: number;
  monitoring_npv: number;
  maintenance_npv: number;
  monitoring: number;
  maintenance: number;
  monitoring_maintenance_npv: number;
  monitoring_maintenance: number;
  community_benefit_npv: number;
  community_benefit: number;
  carbon_standard_fees_npv: number;
  carbon_standard_fees: number;
  baseline_reassessment_npv: number;
  baseline_reassessment: number;
  mrv_npv: number;
  mrv: number;
  long_term_project_operating_npv: number;
  long_term_project_operating: number;
  initial_price_assumption: number;
  leftover_after_opex: number;
  leftover_after_opex_NPV: number;
  total_revenue: number;
  total_revenu_npv: number;
  credits_issued: number;
  price_type: PROJECT_PRICE_TYPE;
};
