name: API Tests

on:
  push:
    paths:
      - 'api/**'
      - 'shared/**'
      - '.github/workflows/api-tests.yml'
      - '/*'               # include changes in root
      - '!client/**'       # exclude client folder
      - '!infrastructure/**'  # exclude infra folder
      - 'package.json'

  workflow_dispatch:


jobs:

  api-tests-integration:
    name: API Integration Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        working-directory: .
        run: pnpm install


      - name: Run API tests
        working-directory: api
        run: pnpm test
