name: API Tests


on:
  push:
    paths:
      - 'api/**'
      - 'shared/**'
      - '.github/workflows/api-tests.yml'
      - '/*'               # include changes in root
      - '!client/**'       # exclude client folder
      - '!infrastructure/**'  # exclude infra folder
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

  workflow_dispatch:


jobs:

  api-tests:
    name: API Tests
    runs-on: ubuntu-22.04

    services:
      database:
        image: postgis/postgis:16-3.4
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: blue-carbon-cost
          POSTGRES_PASSWORD: blue-carbon-cost
          POSTGRES_DB: blc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        working-directory: .
        run: pnpm install

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run API tests
        working-directory: api
        run: pnpm test
