name: e2e Tests

on:
  push:
    paths:
      - 'e2e/**'
      - 'shared/**'
      - 'api/**'
      - 'client/**'
      - 'data/excel/Carbon-Cost Data Upload.xlsm'
      - '.github/workflows/e2e-tests.yml'
      - '/*'               # include changes in root
      - '!infrastructure/**'  # exclude infra folder
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

  workflow_dispatch:


jobs:
  e2e-tests:
    name: e2e tests
    runs-on: ubuntu-22.04

    services:
      database:
        image: postgis/postgis:16-3.4
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: blue-carbon-cost
          POSTGRES_PASSWORD: blue-carbon-cost
          POSTGRES_DB: blc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MinIO
        run: |
          # Faster than docker-compose.test.yml up -d minio in GitHub Actions
          docker run -d \
            -p 9000:9000 \
            -p 9001:9001 \
            -e MINIO_ROOT_USER=testtest \
            -e MINIO_ROOT_PASSWORD=testtest \
            minio/minio server /data --console-address ":9001"

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        working-directory: .
        run: pnpm install

      - name: Install Chromium browser
        working-directory: e2e
        run: npx playwright install --with-deps chromium

      - name: Run e2e tests
        working-directory: e2e
        run: pnpm test:ci

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30